import type { KnowledgeBase } from '@/core/domain/knowledge';
import { ACCOUNT_ID } from './workspace';

export const KNOWLEDGE: KnowledgeBase = {
  categories: [
    {
      id: 'kc-1',
      accountId: ACCOUNT_ID,
      name: 'Primeiros passos',
      description: 'O que o cliente precisa saber na primeira semana.',
      order: 1,
    },
    {
      id: 'kc-2',
      accountId: ACCOUNT_ID,
      name: 'Pagamentos e faturas',
      description: 'Boleto, cartão, segunda via e reembolso.',
      order: 2,
    },
    {
      id: 'kc-3',
      accountId: ACCOUNT_ID,
      name: 'Entrega e prazos',
      description: 'Rastreio, atrasos e política de frete.',
      order: 3,
    },
    {
      id: 'kc-4',
      accountId: ACCOUNT_ID,
      name: 'Conta e segurança',
      description: 'Acesso, senha e dados cadastrais.',
      order: 4,
    },
  ],
  articles: [
    {
      id: 'ka-1',
      accountId: ACCOUNT_ID,
      categoryId: 'kc-1',
      title: 'Como configurar sua conta em 5 minutos',
      slug: 'como-configurar-sua-conta-em-5-minutos',
      excerpt: 'Da criação do acesso ao primeiro atendimento respondido.',
      content:
        'Acesse Configurações → Empresa e preencha os dados da empresa. Em seguida conecte pelo menos uma caixa em Caixas de entrada e cadastre sua equipe em Equipe e Permissões. Toda conversa nova cai na caixa de entrada e fica visível para toda a equipe que alcança aquela caixa. Quem responder primeiro assume o atendimento.',
      status: 'publicado',
      updatedLabel: '12 ago 2026',
      authorName: 'Camila Reis',
      views: 1840,
      helpful: 162,
      notHelpful: 11,
      tags: ['onboarding', 'conta'],
    },
    {
      id: 'ka-2',
      accountId: ACCOUNT_ID,
      categoryId: 'kc-2',
      title: 'Segunda via do boleto',
      slug: 'segunda-via-do-boleto',
      excerpt: 'Emitir um novo boleto quando o vencimento já passou.',
      content:
        'Boletos vencidos podem ser reemitidos pelo próprio portal do cliente, em Faturamento → Faturas. O novo documento mantém o valor original e acrescenta juros proporcionais aos dias de atraso. Após o pagamento, a baixa leva até dois dias úteis.',
      status: 'publicado',
      updatedLabel: '04 ago 2026',
      authorName: 'Rafael Souza',
      views: 3120,
      helpful: 240,
      notHelpful: 38,
      tags: ['boleto', 'pagamento', 'financeiro'],
    },
    {
      id: 'ka-3',
      accountId: ACCOUNT_ID,
      categoryId: 'kc-2',
      title: 'Política de reembolso',
      slug: 'politica-de-reembolso',
      excerpt: 'Prazos e condições para devolução de valores.',
      content:
        'O pedido de reembolso pode ser feito em até 7 dias corridos após a compra. Pagamentos em cartão são estornados na fatura seguinte; pagamentos em boleto ou Pix são devolvidos por transferência em até 10 dias úteis, na mesma titularidade.',
      status: 'publicado',
      updatedLabel: '28 jul 2026',
      authorName: 'Camila Reis',
      views: 970,
      helpful: 61,
      notHelpful: 29,
      tags: ['reembolso', 'estorno'],
    },
    {
      id: 'ka-4',
      accountId: ACCOUNT_ID,
      categoryId: 'kc-3',
      title: 'Como rastrear meu pedido',
      slug: 'como-rastrear-meu-pedido',
      excerpt: 'Onde encontrar o código e o que cada status significa.',
      content:
        'O código de rastreio é enviado por WhatsApp assim que a transportadora coleta o pacote. "Objeto postado" significa que saiu do nosso centro de distribuição; "Em trânsito" indica deslocamento entre unidades; "Saiu para entrega" é o mesmo dia.',
      status: 'publicado',
      updatedLabel: '18 ago 2026',
      authorName: 'Diego Martins',
      views: 5410,
      helpful: 402,
      notHelpful: 24,
      tags: ['entrega', 'rastreio'],
    },
    {
      id: 'ka-5',
      accountId: ACCOUNT_ID,
      categoryId: 'kc-3',
      title: 'O que fazer quando a entrega atrasa',
      slug: 'o-que-fazer-quando-a-entrega-atrasa',
      excerpt: 'Prazo de tolerância e abertura de ocorrência.',
      content:
        'Após dois dias úteis além da data prevista, abra uma ocorrência pelo atendimento informando o número do pedido. A transportadora tem até 5 dias úteis para localizar o pacote; passado esse prazo, reenviamos ou reembolsamos, à sua escolha.',
      status: 'rascunho',
      updatedLabel: '20 ago 2026',
      authorName: 'Diego Martins',
      views: 0,
      helpful: 0,
      notHelpful: 0,
      tags: ['entrega', 'atraso', 'ocorrência'],
    },
    {
      id: 'ka-6',
      accountId: ACCOUNT_ID,
      categoryId: 'kc-4',
      title: 'Redefinir a senha de acesso',
      slug: 'redefinir-a-senha-de-acesso',
      excerpt: 'Recuperação por e-mail e verificação em duas etapas.',
      content:
        'Na tela de login, escolha "Esqueci minha senha" e informe o e-mail cadastrado. O link de redefinição vale por 30 minutos. Se a verificação em duas etapas estiver ativa, o código do aplicativo autenticador continua sendo pedido depois da troca.',
      status: 'publicado',
      updatedLabel: '09 ago 2026',
      authorName: 'Rafael Souza',
      views: 1260,
      helpful: 88,
      notHelpful: 6,
      tags: ['senha', 'acesso', 'segurança'],
    },
    {
      id: 'ka-7',
      accountId: ACCOUNT_ID,
      categoryId: 'kc-1',
      title: 'Glossário de status de conversa',
      slug: 'glossario-de-status-de-conversa',
      excerpt: 'Aberta, pendente, em espera e resolvida: quando usar cada uma.',
      content:
        'Aberta é o atendimento em andamento. Pendente aguarda resposta do cliente. Em espera aguarda uma ação interna (outra área, um prazo). Resolvida encerra o atendimento e dispara a pesquisa de satisfação.',
      status: 'arquivado',
      updatedLabel: '02 jul 2026',
      authorName: 'Camila Reis',
      views: 340,
      helpful: 19,
      notHelpful: 3,
      tags: ['status', 'glossário'],
    },
  ],
};
