import type { Deal, Pipeline } from '@/core/domain/pipeline';
import { ACCOUNT_ID } from './workspace';

const daysAgo = (days: number): string => new Date(Date.now() - days * 86_400_000).toISOString();

export const PIPELINES: readonly Pipeline[] = [
  {
    id: 'pl-comercial',
    accountId: ACCOUNT_ID,
    name: 'Funil Comercial',
    stages: [
      {
        id: 'st-novo',
        pipelineId: 'pl-comercial',
        name: 'Novo Lead',
        order: 1,
        color: '#3B82F6', // Azul
        isWon: false,
        isLost: false,
        conversionWeight: 0,
      },
      {
        id: 'st-qualificacao',
        pipelineId: 'pl-comercial',
        name: 'Qualificação',
        order: 2,
        color: '#F59E0B', // Âmbar
        isWon: false,
        isLost: false,
        conversionWeight: 0,
      },
      {
        id: 'st-proposta',
        pipelineId: 'pl-comercial',
        name: 'Proposta Enviada',
        order: 3,
        color: '#8B5CF6', // Roxo
        isWon: false,
        isLost: false,
        conversionWeight: 0,
      },
      {
        id: 'st-negociacao',
        pipelineId: 'pl-comercial',
        name: 'Negociação',
        order: 4,
        color: '#EC4899', // Magenta / Rosa
        isWon: false,
        isLost: false,
        conversionWeight: 50,
      },
      {
        id: 'st-ganho',
        pipelineId: 'pl-comercial',
        name: 'Fechado Ganho',
        order: 5,
        color: '#10B981', // Verde esmeralda
        isWon: true,
        isLost: false,
        conversionWeight: 100,
      },
      {
        id: 'st-perdido',
        pipelineId: 'pl-comercial',
        name: 'Fechado Perdido',
        order: 6,
        color: '#64748B', // Slate
        isWon: false,
        isLost: true,
        conversionWeight: 0,
      },
    ],
  },
  {
    id: 'pl-suporte',
    accountId: ACCOUNT_ID,
    name: 'Pós-venda & CS',
    stages: [
      {
        id: 'st-onb',
        pipelineId: 'pl-suporte',
        name: 'Onboarding',
        order: 1,
        color: '#3B82F6',
        isWon: false,
        isLost: false,
        conversionWeight: 0,
      },
      {
        id: 'st-ativo',
        pipelineId: 'pl-suporte',
        name: 'Cliente Ativo',
        order: 2,
        color: '#10B981',
        isWon: true,
        isLost: false,
        conversionWeight: 100,
      },
      {
        id: 'st-churn',
        pipelineId: 'pl-suporte',
        name: 'Risco de Churn',
        order: 3,
        color: '#EF4444',
        isWon: false,
        isLost: true,
        conversionWeight: 0,
      },
    ],
  },
];

export const DEALS: readonly Deal[] = [
  {
    id: 'dl-1',
    accountId: ACCOUNT_ID,
    pipelineId: 'pl-comercial',
    stageId: 'st-novo',
    contactId: 'ct-mariana',
    contactName: 'Mariana Costa',
    title: 'Implantação CRM Enterprise',
    company: 'Estúdio MC Fotografia',
    amountInCents: 320_000,
    ownerName: 'Rafael Souza',
    priority: 'media',
    createdAt: daysAgo(1),
    enteredStageAt: daysAgo(1),
    stageAgeLabel: 'há 1 dia',
    nextAction: 'Ligar para apresentar catálogo',
    conversationId: 'cv-mariana',
    source: 'whatsapp',
    history: [{ text: 'Oportunidade criada a partir da conversa WhatsApp', date: '19 ago, 09:14' }],
    tasks: [
      { id: 'tsk-1', title: 'Enviar apresentação institucional', completed: false, dueDate: 'Hoje' },
    ],
  },
  {
    id: 'dl-2',
    accountId: ACCOUNT_ID,
    pipelineId: 'pl-comercial',
    stageId: 'st-novo',
    contactId: 'ct-pedro',
    contactName: 'Pedro Henrique',
    title: 'Plano Pro 5 Usuários',
    company: 'PH Engenharia & Projetos',
    amountInCents: 80_000,
    ownerName: 'Camila Reis',
    priority: 'baixa',
    createdAt: daysAgo(0),
    enteredStageAt: daysAgo(0),
    stageAgeLabel: 'há 3 horas',
    nextAction: 'Enviar catálogo de soluções',
    conversationId: 'cv-pedro',
    source: 'instagram',
    history: [{ text: 'Lead recebido via Direct Instagram', date: '20 ago, 11:05' }],
  },
  {
    id: 'dl-3',
    accountId: ACCOUNT_ID,
    pipelineId: 'pl-comercial',
    stageId: 'st-qualificacao',
    contactId: 'ct-roberta',
    contactName: 'Roberta Dias',
    title: 'Consultoria Omnichannel + Bots',
    company: 'Dias Consultoria',
    amountInCents: 540_000,
    ownerName: 'Rafael Souza',
    priority: 'media',
    createdAt: daysAgo(2),
    enteredStageAt: daysAgo(2),
    stageAgeLabel: 'há 2 dias',
    nextAction: 'Aguardar retorno sobre orçamento',
    conversationId: 'cv-roberta',
    source: 'site',
    history: [
      { text: 'Proposta inicial enviada por e-mail', date: '18 ago, 15:40' },
      { text: 'Reunião de descoberta realizada via Meet', date: '16 ago, 10:00' },
    ],
    tasks: [
      { id: 'tsk-2', title: 'Follow-up de alinhamento técnico', completed: true, dueDate: '17 ago' },
    ],
  },
  {
    id: 'dl-4',
    accountId: ACCOUNT_ID,
    pipelineId: 'pl-comercial',
    stageId: 'st-qualificacao',
    contactName: 'Studio Bella',
    title: 'Automação de Atendimento WhatsApp',
    company: 'Bella Estética Integrada',
    amountInCents: 210_000,
    ownerName: 'Camila Reis',
    priority: 'baixa',
    createdAt: daysAgo(6),
    enteredStageAt: daysAgo(6),
    stageAgeLabel: 'há 6 dias',
    nextAction: 'Follow-up de qualificação urgente',
    source: 'indicacao',
    history: [{ text: 'Sem resposta desde o primeiro contato', date: '14 ago, 09:00' }],
  },
  {
    id: 'dl-5',
    accountId: ACCOUNT_ID,
    pipelineId: 'pl-comercial',
    stageId: 'st-proposta',
    contactId: 'ct-carlos',
    contactName: 'Carlos Eduardo Nunes',
    title: 'Contrato Anual + Integração ERP',
    company: 'Nunes Engenharia SA',
    amountInCents: 1_250_000,
    ownerName: 'Rafael Souza',
    priority: 'alta',
    createdAt: daysAgo(1),
    enteredStageAt: daysAgo(1),
    stageAgeLabel: 'há 1 dia',
    nextAction: 'Confirmar aprovação da diretoria',
    conversationId: 'cv-carlos',
    source: 'google',
    history: [
      { text: 'Orçamento personalizado com SLA enviado', date: '19 ago, 16:02' },
      { text: 'Apresentação para diretoria realizada', date: '15 ago, 14:00' },
    ],
    tasks: [
      { id: 'tsk-3', title: 'Enviar minuta de contrato para jurídico', completed: false, dueDate: 'Amanhã' },
    ],
  },
  {
    id: 'dl-6',
    accountId: ACCOUNT_ID,
    pipelineId: 'pl-comercial',
    stageId: 'st-proposta',
    contactId: 'ct-joao',
    contactName: 'João Pedro Silva',
    title: 'Migração de Telefonia & WhatsApp Cloud',
    company: 'JP Distribuidora',
    amountInCents: 890_000,
    ownerName: 'Camila Reis',
    priority: 'urgente',
    createdAt: daysAgo(9),
    enteredStageAt: daysAgo(9),
    stageAgeLabel: 'há 9 dias',
    nextAction: 'Reenviar proposta e cobrar retorno do CFO',
    conversationId: 'cv-joao',
    source: 'whatsapp',
    history: [{ text: 'Proposta enviada, aguardando aprovação financeira', date: '11 ago, 10:30' }],
  },
  {
    id: 'dl-7',
    accountId: ACCOUNT_ID,
    pipelineId: 'pl-comercial',
    stageId: 'st-negociacao',
    contactId: 'ct-fernanda',
    contactName: 'Fernanda Lopes',
    title: 'Licenciamento Anual 25 Agentes',
    company: 'Fernanda Lopes Studio & Moda',
    amountInCents: 430_000,
    ownerName: 'Rafael Souza',
    priority: 'alta',
    createdAt: daysAgo(2),
    enteredStageAt: daysAgo(2),
    stageAgeLabel: 'há 2 dias',
    nextAction: 'Negociar condição e parcelamento',
    conversationId: 'cv-fernanda',
    source: 'inbound',
    history: [{ text: 'Cliente solicitou condição de parcelamento em 12x', date: '18 ago, 13:20' }],
    tasks: [
      { id: 'tsk-4', title: 'Aprovar condição comercial com financeiro', completed: true, dueDate: '18 ago' },
      { id: 'tsk-5', title: 'Gerar link de pagamento', completed: false, dueDate: 'Hoje' },
    ],
  },
  {
    id: 'dl-8',
    accountId: ACCOUNT_ID,
    pipelineId: 'pl-comercial',
    stageId: 'st-ganho',
    contactId: 'ct-ana',
    contactName: 'Ana Beatriz Rocha',
    title: 'Assinatura Plano Scale',
    company: 'Rocha Importados',
    amountInCents: 160_000,
    ownerName: 'Camila Reis',
    priority: 'baixa',
    createdAt: daysAgo(4),
    enteredStageAt: daysAgo(4),
    stageAgeLabel: 'há 4 dias',
    nextAction: 'Passar bastão para equipe de Onboarding',
    conversationId: 'cv-ana',
    source: 'site',
    history: [{ text: 'Contrato assinado digitalmente e pagamento confirmado', date: '16 ago, 17:42' }],
  },
  {
    id: 'dl-9',
    accountId: ACCOUNT_ID,
    pipelineId: 'pl-comercial',
    stageId: 'st-perdido',
    contactId: 'ct-marcos',
    contactName: 'Marcos Vinícius',
    title: 'Sistema de Call Center',
    company: 'MV Logística & Transportes',
    amountInCents: 670_000,
    ownerName: 'Rafael Souza',
    priority: 'media',
    createdAt: daysAgo(12),
    enteredStageAt: daysAgo(12),
    stageAgeLabel: 'há 12 dias',
    nextAction: 'Agendar contato de reaquecimento em 6 meses',
    source: 'outbound',
    history: [{ text: 'Perdido: cliente optou por solução local prévia', date: '8 ago, 09:00' }],
  },
];
